### PR TITLE
Fix for error by adding headers

### PR DESCRIPTION
**Pull request by sathviksathu**
The fix for issues #1

### CODE REVIEW

**Comment by onkardahale** [comment]
@sathviksathu did not fix the issue
still getting 403

**Comment by arpanagr** [comment]
Yes, still issue is there

**Comment by sathviksathu** [comment]
I am able to get the server responses with this now. I have tested it as well via my script. My script has the following code:
```
headers_dict = {"User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.95 Safari/537.36"}
response = requests.get(url,headers=header_dict)
```

**Comment by onkardahale** [comment]
@sathviksathu 
Sorry my bad. I was working on an online IDE with servers abroad.
Thanks for the fix!

**Comment by sathviksathu** [comment]
Glad to help. 😀

**Comment by arpanagr** [comment]
I already added it and it works mostly but also starts giving 403 in between for sometime..

**Comment by sathviksathu** [comment]
@arpanagr 
As the fix seems to be only a workaround, what you told might be happening, though I have not faced it so far. I will try and look for better solution and update here. Thanks for pointing it out.

**Pull request merged**
